---
heat_template_version: 2013-05-23
outputs:
  public_ip:
    description: "public IP address of the deployed compute instance"
    value:
      get_attr:
        - compute_instance
        - accessIPv4
parameters:
  name:
    default: CoreOS-Stack
    description: "Name of booted CoreOS machine"
    type: string
  flavor:
    type: string
  image:
    type: string
  location:
    type: string
  du:
    type: string
  publish_ports:
    type: string
resources:
  compute_instance:
    properties:
      config_drive: "true"
      flavor: {get_param: flavor}
      image: {get_param: image}
      name: {get_param: name}
      user_data:
        str_replace:
          template:
            get_file: robust-du-handling.sh
          params:
            "%location%": { get_param: location }
            "%du%": { get_param: du }
            "%publish_ports%": { get_param: publish_ports }
            wc_notify: { get_attr: ['wait_handle', 'curl_cli'] }

      user_data_format: RAW
    type: "OS::Nova::Server"

  wait_on_server:
    type: OS::Heat::SwiftSignal
    properties:
      handle: {get_resource: wait_handle}
      count: 1
      timeout: 600

  wait_handle:
    type: OS::Heat::SwiftSignalHandle