#!/bin/bash

# Slugbuilder builds the cedarish slug
# We should own/customize this for solum
# but for POC we can grab and build container
echo Creating slugbuilder container
sudo docker build -t solum/slugbuilder github.com/paulczar/slugbuilder

# Slugrunner runs the cedarish slug built
# by slugbuilder.
# We should own/customize this for solum
# but for POC we can grab and build container
echo Creating slugrunner container
sudo docker build -t solum/slugrunner github.com/paulczar/slugrunner


echo Preparing Buildpacks
sudo mkdir -p /opt/solum/buildpacks
sudo chown -R ${USER}:${USER} /opt/solum
cd /opt/solum/buildpacks
# These buildpacks help with autodetection and app level depedency installs.
git clone --depth 1 https://github.com/heroku/heroku-buildpack-java.git
git clone --depth 1 https://github.com/heroku/heroku-buildpack-ruby.git
git clone --depth 1 https://github.com/heroku/heroku-buildpack-python.git
git clone --depth 1 https://github.com/gabrtv/heroku-buildpack-nodejs
git clone --depth 1 https://github.com/heroku/heroku-buildpack-play.git
git clone --depth 1 https://github.com/CHH/heroku-buildpack-php.git
git clone --depth 1 https://github.com/heroku/heroku-buildpack-clojure.git
git clone --depth 1 https://github.com/kr/heroku-buildpack-go.git
git clone --depth 1 https://github.com/heroku/heroku-buildpack-scala
git clone --depth 1 https://github.com/igrigorik/heroku-buildpack-dart.git
git clone --depth 1 https://github.com/miyagawa/heroku-buildpack-perl.git

mkdir -p /opt/solum/apps
mkdir -p /opt/solum/cache