#!/bin/bash

apt-get update && apt-get install -y openjdk-7-jre-headless wget
wget -q -O - http://pkg.jenkins-ci.org/debian/jenkins-ci.org.key | apt-key add -
echo deb http://pkg.jenkins-ci.org/debian binary/ > /etc/apt/sources.list.d/jenkins.list
apt-get update && apt-get install -y jenkins
