#!/bin/bash

DOCKER_REGISTRY=${DOCKER_REGISTRY:-'127.0.0.1:5042'}

sudo mkdir -p /opt/solum
sudo chown -R ${USER}:${USER} /opt/solum

sudo mkdir -p /var/log/solum
sudo chown -R ${USER}:${USER} /var/log/solum

mkdir -p /opt/solum/apps
