#!/bin/bash

GIT_DIR=/home/git

mkdir -p $GIT_DIR/admin_keys
mkdir -p $GIT_DIR/bin

install-packages git openssh-server

locale-gen en_US.UTF-8
dpkg-reconfigure locales

mkdir /var/run/sshd

adduser --system --group --shell /bin/sh git

git clone git://github.com/sitaramc/gitolite $GIT_DIR/source
cd $GIT_DIR
source/install -to $GIT_DIR/bin
