#!/bin/bash

DIR=$(dirname $0)

# uncomment this if we want to auto build/download cedarish vm
#ACTION=$1
#shift
#: ${ACTION:='download-cedarish'}

# great security practice in 3 ... 2 ... 1 ...
# install docker
echo Install docker:
[[ -f /usr/bin/docker ]] || $DIR/get_docker_io.sh

# We'll be doing VM builds
echo Prepare image-builder:
. $DIR/../vm/prepare

# We'll be doing docker stuff
echo prepare slug building environment:
. $DIR/../docker/prepare

# we need a docker container to host slugs
# this should end up being swift or glance or something
mkdir -p /opt/solum/apps
sudo docker pull kstaken/apache2
sudo docker run -d -v /opt/solum/apps:/var/www:ro -p 0.0.0.0:8080:80 -name slugweb kstaken/apache2

mkdir -p /opt/solum/slugs

case $ACTION in
'build-cedarish')
  . $DIR/build-cedarish
  ;;
'download-cedarish')
  . $DIR/download-cedarish
  ;;
esac