- hosts: all
  name: Autoconverted job legacy-solum-devstack-py35 from old job gate-solum-devstack-dsvm-py35-ubuntu-xenial-nv
  tasks:

    - name: Ensure legacy workspace directory
      file:
        path: '{{ ansible_user_dir }}/workspace'
        state: directory

    - shell:
        cmd: |
          set -e
          set -x
          cat > clonemap.yaml << EOF
          clonemap:
            - name: openstack-infra/devstack-gate
              dest: devstack-gate
          EOF
          /usr/zuul-env/bin/zuul-cloner -m clonemap.yaml --cache-dir /opt/git \
              https://git.openstack.org \
              openstack-infra/devstack-gate
        executable: /bin/bash
        chdir: '{{ ansible_user_dir }}/workspace'
      environment: '{{ zuul | zuul_legacy_vars }}'

    - shell:
        cmd: |
          set -e
          set -x
          cat << 'EOF' >>"/tmp/dg-local.conf"
          [[local|localrc]]
          TEMPEST_PLUGINS='/opt/stack/new/solum-tempest-plugin'
          enable_plugin solum https://git.openstack.org/openstack/solum
          SOLUM_PROJ_DIR=/opt/stack/new/solum
          enable_plugin zun https://git.openstack.org/openstack/zun
          enable_plugin devstack-plugin-container https://git.openstack.org/openstack/devstack-plugin-container

          EOF
        executable: /bin/bash
        chdir: '{{ ansible_user_dir }}/workspace'
      environment: '{{ zuul | zuul_legacy_vars }}'

    - shell:
        cmd: |
          set -e
          set -x
          export DEVSTACK_GATE_USE_PYTHON3=True
          export PYTHONUNBUFFERED=true
          export DEVSTACK_GATE_NEUTRON=1
          export ENABLED_SERVICES=solum,solum-api,solum-conductor,solum-deployer,solum-worker,tempest,zaqar,barbican,mistral
          export PROJECTS="openstack/solum  $PROJECTS"
          export PROJECTS="openstack/solum-dashboard $PROJECTS"
          export PROJECTS="openstack/python-solumclient $PROJECTS"
          export PROJECTS="openstack/barbican $PROJECTS"
          export PROJECTS="openstack/mistral $PROJECTS"
          export PROJECTS="openstack/zun $PROJECTS"
          export PROJECTS="openstack/devstack-plugin-container $PROJECTS"
          export PROJECTS="openstack/python-zunclient $PROJECTS"
          export PROJECTS="openstack/zun-tempest-plugin $PROJECTS"
          export PROJECTS="openstack/solum-tempest-plugin $PROJECTS"

          export KEEP_LOCALRC=1

          function pre_test_hook {
              cd /opt/stack/new/solum/functionaltests
              ./pre_test_hook.sh
          }
          export -f pre_test_hook

          function gate_hook {
              cd /opt/stack/new/solum/functionaltests
              ./gate_hook.sh
          }
          export -f gate_hook

          function post_test_hook {
              cd /opt/stack/new/solum/functionaltests
              ./post_test_hook.sh
          }
          export -f post_test_hook

          cp devstack-gate/devstack-vm-gate-wrap.sh ./safe-devstack-vm-gate-wrap.sh
          ./safe-devstack-vm-gate-wrap.sh
        executable: /bin/bash
        chdir: '{{ ansible_user_dir }}/workspace'
      environment: '{{ zuul | zuul_legacy_vars }}'
