#!/bin/bash

echo $0

echo "Install some prereqs"

sudo apt-get -yqq update
sudo apt-get -yqq install qemu-utils git curl wget

echo "install disk image builder"

if [[ -d /opt/disk-image-builder ]]; then
  sudo git clone https://github.com/openstack/diskimage-builder.git /opt/disk-image-builder
  cd /opt/disk-image-builder
  sudo pip install .
fi

sudo mkdir -p /opt/solum/apps

sudo chown -R ${USER}:${USER} /opt/solum
